[[redirects]]
  from = "/pagina2.html"
  to = "/pagina2"
  status = 200
  force = true

  

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/pedido.html"
  to = "/pedido"
  status = 200
  force = true 
 